ALTER TABLE `tenant`
    ADD COLUMN `document` VARCHAR(191) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL,
    ADD COLUMN `email` VARCHAR(191) NULL,
    ADD COLUMN `address` VARCHAR(191) NULL,
    ADD COLUMN `logoUrl` VARCHAR(512) NULL;
